USE `hotel_db`

-- 1. Tắt kiểm tra khóa ngoại để tránh lỗi ràng buộc khi xóa dữ liệu
SET FOREIGN_KEY_CHECKS = 0;

-- 2. Xóa sạch dữ liệu trong các bảng
TRUNCATE TABLE `DANH_GIA`;
TRUNCATE TABLE `THANH_TOAN`;
TRUNCATE TABLE `SU_DUNG_DV`;
TRUNCATE TABLE `CHI_TIET_DAT_PHONG`;
TRUNCATE TABLE `DON_DAT_PHONG`;
TRUNCATE TABLE `HINH_ANH_PHONG`;
TRUNCATE TABLE `PHONG`;
TRUNCATE TABLE `LOAI_PHONG`;
TRUNCATE TABLE `DICH_VU`;
TRUNCATE TABLE `KHACH_HANG`;
TRUNCATE TABLE `NGUOI_DUNG`;
TRUNCATE TABLE `VAI_TRO`;

-- 3. Bật lại kiểm tra khóa ngoại
SET FOREIGN_KEY_CHECKS = 1;